/* ================================================
- Module Name: Types
- Purpose: header file for types and defines the
different types needed and global defines
================================================ */
#ifndef TYPES_H
#define TYPES_H
#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 400
#define BITMAP_MAX 32
#define BITMAP_MIN 8
#define BYTES_PER_SCREEN 32000
#define SPLASH_MAX 16000

typedef unsigned char UINT8;
typedef unsigned long UINT32;
typedef unsigned long ULONG32;
#endif