/* ================================================
- Module Name: bitmaps
- Purpose: header file for bitmaps.c
================================================ */
#ifndef BITMAPS_H
#define BITMAPS_H
#include "../global/TYPES.H"
extern UINT8 splash_endGameScore0[];
extern UINT8 splash_endGame[]; 
extern UINT8 splash_welcome[];
extern UINT8 bullet_bitmapLeft[BITMAP_MIN];
extern UINT8 bullet_bitmapRight[BITMAP_MIN];
extern UINT8 bullet_bitmapUp[BITMAP_MIN];
extern UINT8 bullet_bitmapDown[BITMAP_MIN];
extern UINT8 point_bitmap[BITMAP_MIN];

extern UINT32 gangster_bitmap_right[BITMAP_MAX];
extern UINT32 gangster_bitmap_left[BITMAP_MAX];
extern UINT32 gangster_bitmap_down[BITMAP_MAX];
extern UINT32 gangster_bitmap_up[BITMAP_MAX];

extern UINT32 zombie_bitmap_right[BITMAP_MAX];
extern UINT32 zombie_bitmap_left[BITMAP_MAX];
extern UINT32 zombie_bitmap_down[BITMAP_MAX];
extern UINT32 zombie_bitmap_up[BITMAP_MAX];

extern UINT32 selection_bitmap[BITMAP_MAX];

extern UINT32 font_ch_0[BITMAP_MAX];
extern UINT32 font_ch_1[BITMAP_MAX];
extern UINT32 font_ch_2[BITMAP_MAX];
extern UINT32 font_ch_3[BITMAP_MAX];
extern UINT32 font_ch_4[BITMAP_MAX];
extern UINT32 font_ch_5[BITMAP_MAX];
extern UINT32 font_ch_6[BITMAP_MAX];
extern UINT32 font_ch_7[BITMAP_MAX];
extern UINT32 font_ch_8[BITMAP_MAX];
extern UINT32 font_ch_9[BITMAP_MAX];

extern UINT32 font_ch_L[BITMAP_MAX];
extern UINT32 font_ch_I[BITMAP_MAX];
extern UINT32 font_ch_V[BITMAP_MAX];
extern UINT32 font_ch_E[BITMAP_MAX];
extern UINT32 font_ch_S[BITMAP_MAX];
extern UINT32 font_ch_C[BITMAP_MAX];
extern UINT32 font_ch_O[BITMAP_MAX];
extern UINT32 font_ch_R[BITMAP_MAX];

#endif